version: "3"
services:
  web:
    image: "myfirstproj:latest"
    ports:
      - "4200:80"
  nest:
    image: "book-store-backend:dev"
    environment:
      DB_HOST : 'localhost'
      PORT : 3307
    ports:
      - "3000:3000" 
  mysql:
    image: mysql/mysql-server
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD : MySQLSerafym19
      MYSQL_DATABASE: users
    ports:
      - "3307:3306"
    restart: always